### ISSUE TITLE
Route returns 404 when param name changes in a child route

### ISSUE THREAD

**Issue by nadeesha** [splinter/jaggery-pipe#2]
Given route `A`:
`app.get('/:context/conferences/:id'...`

and Route `B`:
`app.post('/:context/conferences/:confId/agendas'...`

(note change in params `:id` vs `:confId`)

and `A` precedes `B`,

`A` will return a 404.

However,changing `A` to: 
`app.get('/:context/conferences/:confid'...`

Will make both work.

**Comment by splinter** [comment]
The problem is caused by these few lines:

jaggery-pipe / plugins / router / scripts / util / route-map.js line 130 -132

When a route is added to the Route Map, we look for dynamic values (e.g. : id or :confId). If a dynamic value is found then that value automatically becomes the default route for that level.

We could do two things;
1. Silently consider confId as equivalent to id and drop it
2. Throw an exception indicating that a dynamic value has been registered for that level of the route tree and the user should check his routes.

WDYT?

**Comment by nadeesha** [comment]
I think it's best to go for option 1 because:
- expressjs does the same.
- a route should be totally independent from any other routes, and it's only concern should be middleware and the handler.
- only middleware and handlers would be concerned about the name of the parameter.
